---
- hosts: wordpress
  become: true
  remote_user: ec2-user
  tasks:
    - name: Deploy WordPress
      docker_container:
        image: wordpress
        name: wordpress
        restart_policy: always
        ports:
          - "8080:80"
        env:
          WORDPRESS_DB_PASSWORD: "{{ wp_pass }}"
          WORDPRESS_DB_NAME: mydb
          WORDPRESS_DB_USER: wordpress_user
          WORDPRESS_DB_HOST: "{{ mysql_host }}"
