---
- hosts: wordpress
  become: true
  remote_user: ec2-user
  tasks:
    - name: Deploy WordPress
      docker_container:
        image: wordpress
        name: wordpress
        restart_policy: always
        ports:
          - "8080:80"
        env:
          MYSQL_PASSWORD: wordpress
          MYSQL_DATABASE: mydb
          MYSQL_USER: wordpress
          MYSQL_HOST: terraform-20230922122021403900000001.cr8gqagh3l5w.us-east-1.rds.amazonaws.com
