name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  example-job:
    name: Deploy Wordpress on aws      
    runs-on: ubuntu-latest
    env:
        TF_VERSION: latest
        TF_WORKING_DIR: terraform

    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}


      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: true

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: true

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
          tf_actions_comment: true

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        if: github.event_name == 'push'
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}

      - name: Run ansible script
        shell: bash 
        run: |
          cd terraform
          terraform output | grep elastic_ip | awk -F'"' '/"/ {print $2}' >> ../ansible/inventory
          mysql_host=$(terraform output | grep db_ip | awk -F'"' '/"/ {print $2}')
          cd ..
          ansible-playbook ansible/wordpress-playbook.yaml -i ansible/inventory -e mysql_host=$mysql_host -e wp_pass=${{ env.WORDPRESS_DB_PASSWORD}} --ssh-common-args='-o StrictHostKeyChecking=no'


#      - name: Make the script files executable
#        run: chmod +x script.sh
#      - name: Run the scripts
#        run: |
#          ./script.sh
