name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  example-job:
    name: Deploy Wordpress on aws      
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: aca_project
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}    
      - name: Git clone repository
        run: git clone git@github.com:hamo050/aca_project.git
      - name: ls
        run: `ls -la`
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}

            
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x script.sh
      - name: Run the scripts
        run: |
          ./script.sh
